# Global settings
# Not reloaded automatically when you use 'bundle exec jekyll serve'
# If you change this file, restart the server process

# Site settings, accessed via {{ site.title }}, {{ site.email }}, etc.
# Create custom variable via {{ site.myvariable }}

#{{ site.title }}
title: jstnlowe.com

#{{ site.email }}
email: blog@jstnlowe.com
description: >- # ignore newlines until "baseurl:"
  do what you can, with what you have, where you are
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jstnlowe.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jstnlowe
github_username:  jstnlowe

# Build Settings
remote_theme: "mmistakes/minimal-mistakes" 
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/